### ISSUE TITLE
1.20.1 - Unregistered recipe for (any) storage drawers.

### ISSUE THREAD

**Issue by RealSourceOfficial** [jaquadro/StorageDrawers#1111]
StorageDrawers (v1.20.1-1.20.2, forge v47.2.16) currently does not have recipes to craft any of the drawers, trims, upgrades, keys, or any other item added by the mod

## Affected Versions (will be expanded as more versions are tested):
- [x] 1.20.2
- [x] 1.20.1
- [x] 1.19.2

## Related logs:
<details>
<summary> 

### KubeJS Server 

</summary>

```log
Failed to parse recipe 'storagedrawers:conversion_upgrade[minecraft:crafting_shaped]'! Falling back to vanilla: ItemStack 'result' can't be empty!
```

</details>
<details>
<summary>

### Forge 

</summary>

```
[10:51:29] [main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe storagedrawers:conversion_upgrade com.google.gson.JsonSyntaxException: Unknown item 'storagedrawers:conversion_upgrade' at net.minecraftforge.common.crafting.CraftingHelper.getItem(CraftingHelper.java:160) ~[forge-1.20.1-47.1.3-universal.jar%23120!/:?] {re:classloading}
```

```log
[13:36:38] [main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe storagedrawers:conversion_upgrade
com.google.gson.JsonSyntaxException: Unknown item 'storagedrawers:conversion_upgrade'
at net.minecraftforge.common.crafting.CraftingHelper.getItem(CraftingHelper.java:160) ~[forge-1.20.1-47.1.0-universal.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:186) ~[forge-1.20.1-47.1.0-universal.jar%23188!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.world.item.crafting.ShapedRecipe.m_151274_(ShapedRecipe.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.item.crafting.AccessorShapedRecipe,pl:mixin:A}
at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:311) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:classloading}
at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6729_(ShapedRecipe.java:301) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:classloading}
at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.20.1-47.1.0-universal.jar%23188!/:?] {re:classloading}
at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:171) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,re:computing_frames,re:classloading}
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:classloading}
at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:classloading}
at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23183!/:?] {re:mixin,re:classloading,pl:mixin:APP:create.mixins.json:MainMixin,pl:mixin:A}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.0.jar%2369!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

</details>

## Related issues:
#1098
#1043
#1056

## Screenshots:
![image](https://github.com/jaquadro/StorageDrawers/assets/65256422/23b6786c-2bd0-476e-9888-0fe4a3175160)
![image](https://github.com/jaquadro/StorageDrawers/assets/65256422/0ae3c956-157c-4ec4-8b7a-7313476e544d)
![image](https://github.com/jaquadro/StorageDrawers/assets/65256422/217da55a-654e-46bf-ae14-d89e87af9bfc)
![image](https://github.com/jaquadro/StorageDrawers/assets/65256422/b9596f43-6e59-4f63-9671-57708d3edb4d)

<details>
<summary> 

## Modlist: 

</summary>
<br>

```log
[10Dec2023 10:02:07.221] [main/INFO] [Puzzles Lib/]: Loading 186 mods:
	- ae2 15.0.15
	- ae2wtlib 15.1.5-forge
	- aiimprovements 0.5.2
	- alchemistry 2.3.4
	- alchemylib 1.0.29
	- alltheores 2.2.3
	- almostunified 1.20.1-0.7.2
	- apotheosis 7.1.0
	- appleskin 2.5.1+mc1.20.1
	- appmek 1.4.2
	- architectury 9.1.12
	- athena 3.1.1
	- attributefix 21.0.4
	- attributeslib 1.2.0
	- badpackets 0.4.3
	- balm 7.1.4
	- betteradvancements 0.3.2.161
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterendisland 1.20-Forge-2.0.4
	- betterfortresses 1.20-Forge-2.0.5
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- bookshelf 20.1.6
	- botarium 2.2.1
	- bwncr 3.17.0
	- chemlib 2.0.18
	- clean_tooltips 1.0
	- cloth_config 11.1.106
	- clumps 12.0.0.3
	- colorfulhearts 4.0.4
	- comforts 6.3.4+1.20.1
	- commoncapabilities 2.9.0
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- coolcat_lib 1.0.1
	- craftingtweaks 18.2.1
	- create 0.5.1.f
	- create_confectionery 1.1.0
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.g
	- create_new_age 1.0.1b
	- createaddition 1.20.1-1.2.0b
	- createbb 3.1.1
	- createchromaticreturn 1.0.0
	- createdieselgenerators 1.20.1-1.2e
	- creategoggles 0.5.5.e_hf
	- createliquidfuel 2.0.2-1.20.1
	- createoreexcavation 1.4.1
	- createsweetsandtreets 1.0.0
	- cupboard 1.20.1-2.1
	- curios 5.4.5+1.20.1
	- cyclopscore 1.18.14
	- darkmodeeverywhere 1.20.1-1.2.2
	- darkutils 17.0.3
	- drawerstooltip 8.0.0
	- durability101 0.0.4
	- elevatorid 1.20.1-lex-1.9
	- emi 1.0.26+1.20.1+forge
	- emiffect 1.1.2+mc1.20.1
	- emitrades 1.2.1+mc1.20.1
	- enchdesc 17.0.9
	- enderio 6.0.23-alpha
	- entityculling 1.6.2
	- equipmentcompare 1.3.7
	- exchangers 1.20.1-3.5.1
	- explorerscompass 1.20.1-1.3.3-forge
	- extremesoundmuffler 3.41-forge-1.20
	- farmersdelight 1.20.1-1.2.3
	- fastbench 8.0.2
	- fastfurnace 8.0.1
	- fastleafdecay 31
	- fastload 3.4.0
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- flywheel 0.6.10-7
	- forbidden_arcanus 1.20.1-2.2.3
	- forge 47.2.16
	- ftbbackups2 1.0.23
	- ftbchunks 2001.2.3
	- ftbessentials 2001.2.2
	- ftblibrary 2001.1.4
	- ftbqoptimizer 1.1.4-1.20.1
	- ftbquests 2001.2.0
	- ftbranks 2001.1.3
	- ftbteams 2001.1.4
	- ftbultimine 2001.1.2
	- ftbxmodcompat 2.0.3
	- gamestages 15.0.1
	- geckolib 4.2.4
	- globalpacks 1.16.2_forge
	- gunpowderlib 1.20.2-2.2.1
	- iceberg 1.1.16
	- industrialforegoing 3.5.9
	- integratedcrafting 1.1.6
	- integrateddynamics 1.20.2
	- integrateddynamicscompat 1.20.2
	- integratedrest 1.1.10
	- integratedterminals 1.4.11
	- integratedterminalscompat 1.4.11
	- integratedtunnels 1.8.24
	- integratedtunnelscompat 1.8.24
	- inventoryhud 3.4.18
	- inventorysorter 23.0.1
	- ironchest 1.20.1-14.4.4
	- itemfilters 2001.1.0-build.59
	- jearchaeology 1.20.1-1.0.3
	- jei 15.2.0.27
	- jei_mekanism_multiblocks 4.2
	- jeresources 1.4.0.238
	- justzoom 1.0.2
	- konkrete 1.6.1
	- kotlinforforge 4.7.0
	- kubejs 2001.6.4-build.95
	- kubejs_create 2001.2.5-build.2
	- lootintegrations 1.20.1-3.4
	- lootjs 2.10.3
	- lootr 0.7.29.68
	- maptooltip 3.0.1
	- mcjtylib 1.20-8.0.3
	- megacells 2.2.6-1.20.1
	- mekanism 10.4.5
	- mekanismgenerators 10.4.5
	- mekanismtools 10.4.5
	- minecraft 1.20.1
	- mixinextras 0.2.1-beta.2
	- moonlight 1.20-2.8.67
	- morejs 0.4.0
	- moremekanismprocessing 4.0
	- moreoverlays 1.22.1-mc1.20
	- mousetweaks 2.25
	- mutil 6.1.1
	- myserveriscompatible 1.0
	- naturescompass 1.20.1-1.11.2-forge
	- neat 1.20-35-FORGE
	- nethersdelight 1.20.1-4.0
	- nochatreports 1.20.1-v2.2.2
	- notenoughcrashes 4.4.6+1.20.1
	- overloadedarmorbar 1.20.1-1
	- patchouli 1.20.1-83-FORGE
	- pickupnotifier 8.0.0
	- pigpen 15.0.2
	- placebo 8.6.0
	- pneumaticcraft 6.0.11+mc1.20.1
	- polylib 2000.0.3-build.97
	- polymorph 0.49.1+1.20.1
	- ponderjs 1.3.0
	- probejs 5.5.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.9
	- reap 1.20.1-1.0.2
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.18
	- rftoolsbase 1.20-5.0.2
	- rhino 2001.2.2-build.13
	- runelic 18.0.2
	- saturn 0.0.7
	- sdrp 4.0.2-build.36+mc1.20.1
	- searchables 1.0.2
	- shulkerboxtooltip 4.0.4+1.20.1
	- simplebackups 1.20.1-3.1.2
	- simpleconfig 1.20.1-1.0.4
	- sliceanddice 3.2.0
	- solapplepie 1.20.1-2.3.0
	- sophisticatedbackpacks 3.19.1.962
	- sophisticatedcore 0.5.108.504
	- spark 1.10.53
	- spectrelib 0.13.14+1.20.1
	- storagedrawers 12.0.2
	- tempad 2.1.1
	- tetra 6.1.0
	- theoneprobe 1.20.1-10.0.1
	- tipsmod 12.0.4
	- titanium 3.8.23
	- toastcontrol 8.0.3
	- tombstone 8.5.5
	- toofast 0.4.3.5
	- ultimine_addition 1.1.1
	- valhelsia_core 1.1.1
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- yungsapi 1.20-Forge-4.0.2
	- yungsmenutweaks 1.20.1-Forge-1.0.1
	- zerocore 1.20.1-2.1.40
```

</details>

**Comment by RealSourceOfficial** [comment]
Well, the issue is fixed. Turned out KubeJS removed all in-game recipes by accident.
