### ISSUE TITLE
Crash after Multipart update

### ISSUE THREAD

**Issue by twothe** [jaquadro/StorageDrawers#114]
I never had any crashes with my setup till today, when I updated ForgeMultipart and Project Red to the latest version. Not sure if it is related at all, just wanted to mention it.

When I logged back in half of the 2x2 full drawers (all of the exact same type and material) were not rendered, and when I right-clicked into seemingly the air, which would have taken an item from the drawer, the game crashed.

Crash report:
```
[28/6/2015 14:25:04 PM] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel StorageDrawers
[28/6/2015 14:25:04 PM] java.lang.NullPointerException
[28/6/2015 14:25:04 PM] 	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawers.clientUpdateCount(TileEntityDrawers.java:502) ~[TileEntityDrawers.class:?]
[28/6/2015 14:25:04 PM] 	at com.jaquadro.minecraft.storagedrawers.network.CountUpdateMessage$Handler.onMessage(CountUpdateMessage.java:62) ~[CountUpdateMessage$Handler.class:?]
[28/6/2015 14:25:04 PM] 	at com.jaquadro.minecraft.storagedrawers.network.CountUpdateMessage$Handler.onMessage(CountUpdateMessage.java:53) ~[CountUpdateMessage$Handler.class:?]
[28/6/2015 14:25:04 PM] 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
[28/6/2015 14:25:04 PM] 	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[28/6/2015 14:25:04 PM] 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[28/6/2015 14:25:04 PM] 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[28/6/2015 14:25:04 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[28/6/2015 14:25:04 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 14:25:04 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 14:25:04 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[28/6/2015 14:25:04 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[28/6/2015 14:25:04 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by jaquadro** [comment]
Look further back in the log for something related to TileEntities failing to load.  The network crash is a symptom of an earlier error or corruption.

**Comment by jaquadro** [comment]
Closing due to no further feedback or other reports of crashing.  Most likely, it was chunk corruption.
