### ISSUE TITLE
1.21.3 Fabric - Crash

### ISSUE THREAD

**Issue by RustH077** [jaquadro/StorageDrawers#1169]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-10-31 12:10:00
Description: Rendering screen

java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:412)
	at knot//net.minecraft.class_4587.method_22903(class_4587.java:527)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:177)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:129)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244)
	at knot//me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at knot//net.minecraft.class_465.handler$zcd000$architectury$renderBackground(class_465.java:802)
	at knot//net.minecraft.class_465.method_25420(class_465.java:187)
	at knot//net.minecraft.class_437.method_25394(class_437.java:125)
	at knot//net.minecraft.class_465.method_25394(class_465.java:118)
	at knot//net.minecraft.class_481.method_25394(class_481.java:792)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$56(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bff000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:412)
	at knot//net.minecraft.class_4587.method_22903(class_4587.java:527)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:177)
	at knot//me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:129)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109)
	at knot//me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:347)
	at knot//me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244)
	at knot//me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
	at knot//me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
	at knot//net.minecraft.class_465.handler$zcd000$architectury$renderBackground(class_465.java:802)
	at knot//net.minecraft.class_465.method_25420(class_465.java:187)
	at knot//net.minecraft.class_437.method_25394(class_437.java:125)
	at knot//net.minecraft.class_465.method_25394(class_465.java:118)
	at knot//net.minecraft.class_481.method_25394(class_481.java:792)
	at knot//net.minecraft.class_437.method_47413(class_437.java:116)
	at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$56(class_757.java)
	at knot//net.minecraft.class_757.wrapOperation$bff000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.error.ErrorsScreen
	Mouse location: Scaled: (730, 257). Absolute: (1461.000000, 515.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:549)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 23.431s
	Wall uptime: 15.916s
	High-res time: 13.382s
	Client ticks: 189 ticks / 9.450s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['RustH077'/117, l='ClientLevel', x=-923.30, y=66.00, z=-518.96]]
	Chunk stats: 1521, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (-928,68,-512), Section: (at 0,4,0 in -58,4,-32; chunk contains blocks -928,-64,-512 to -913,319,-497), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 5381 game time, 5381 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 169

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/VanillaTweaks_r879063_MC1.21.x.zip, fabric, axesareweapons, balm-fabric, clean-debug, cloth-config, conditional-mixin, durabilitytooltip, expandedstorage, extremesoundmuffler, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fluidtank, health_levels, inventorytweak, itemcollectors, jade, jamlib, jankson, kotori_scala, lambdynlights, libgui, merenc, midnightlib, modmenu, moreculling, mr_recipes_plus, noexpensive, owo, pride, rightclickharvest, roughlyenoughitems, silk-all, sodium, sodium-extra, spruceui, stack-to-nearby-chests, storagedrawers, supermartijn642corelib, taxfreelevels, trade_cycling, veinminer, veinminer-enchantment, waystones

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 564326512 bytes (538 MiB) / 1409286144 bytes (1344 MiB) up to 15032385536 bytes (14336 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 8176.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.24033.1003
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 18472.10
	Virtual memory used (MiB): 14434.78
	Swap memory total (MiB): 2164.68
	Swap memory used (MiB): 112.21
	Space in storage for jna.tmpdir (MiB): available: 172337.23, total: 249191.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 172337.23, total: 249191.00
	Space in storage for io.netty.native.workdir (MiB): available: 172337.23, total: 249191.00
	Space in storage for java.io.tmpdir (MiB): available: 172337.23, total: 249191.00
	Space in storage for workdir (MiB): available: 172337.23, total: 249191.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 14.0.4
		axesareweapons: Axes Are Weapons 1.9.3
		balm-fabric: Balm 21.3.3
			kuma_api: KumaAPI 21.3.1-SNAPSHOT
		better_craftables: Better Craftables 3.0.0
		clean-debug: Clean F3 0.4.8
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.89
		doubledoors: Double Doors 6.0
		durabilitytooltip: Durability Tooltip 1.1.5
		expandedstorage: Expanded Storage 15.0.0-beta.1
		extremesoundmuffler: Extreme Sound Muffler 3.48.4
			fiber: fiber 0.23.0-2
		fabric-api: Fabric API 0.107.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.49+d21566ae40
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.79+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+6c3b5d4940
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.3+c47b9d4340
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.23+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.57+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.36+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.74+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.6+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+1ff58ec240
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+d9873d8b40
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.15+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.6+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.10+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.6+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.16+e7c9ab6640
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4340
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+4402f4ee40
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.25+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.13+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.20+c47b9d4340
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.8+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.4+89cb0a4e40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.8+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.9+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.3+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.1+89cb0a4e40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.4+c47b9d4340
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.4+c47b9d4340
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.14+c47b9d4340
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.82+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.6+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+e82f21f740
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.33+c47b9d4340
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.99+c47b9d4340
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		fluidtank: Fluid Tank 21.3.0
		furnacerecycle: Furnace Recycle 2.6
		health_levels: Health Levels 1.0.10
		infinitetrading: Infinite Trading 4.5
		inventorytotem: Inventory Totem 3.3
		inventorytweak: Inventory Tweak 3.0
		itemcollectors: Item Collectors 1.1.10
		jade: Jade 16.0.4+fabric
		jamlib: JamLib 1.2.2+1.21.3
			blue_endless_jankson: jankson 1.2.3
		java: OpenJDK 64-Bit Server VM 21
		kotori_scala: Scalable Cat's Force Fabric 3.1.3
			org_scala-lang_scala-library: scala-library 2.13.14
			org_scala-lang_scala3-library_3: scala3-library_3 3.5.1
			org_typelevel_cats-core_3: cats-core_3 2.12.1-kotori
			org_typelevel_cats-free_3: cats-free_3 2.12.1-kotori
			org_typelevel_cats-kernel_3: cats-kernel_3 2.12.1-kotori
		lambdynlights: LambDynamicLights 3.2.2+1.21.3
			pride: Pride Lib 1.3.0+1.21.2
			spruceui: SpruceUI 6.1.0+1.21.2
		merenc: Merge Enchantments 4.0
		midnightlib: MidnightLib 1.6.4
		minecraft: Minecraft 1.21.3
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moreculling: More Culling 1.1.0-beta.2
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		mousetweaks: Mouse Tweaks 2.27
		mr_nbc: Netherite But Cheaper 2.3
		mr_recipes_plus: Recipes Plus 1.3.5
		noexpensive: NoExpensive 1.21.3-1.10.0
		owo: oωo 0.12.17+1.21.2
			io_wispforest_endec: endec 0.1.9
			io_wispforest_endec_gson: gson 0.1.6
			io_wispforest_endec_jankson: jankson 0.1.6
			io_wispforest_endec_netty: netty 0.1.5
		passiveshield: Passive Shield 3.6
		rightclickharvest: Right Click Harvest 4.4.2+1.21.3
		roughlyenoughitems: Roughly Enough Items 17.0.789
			error_notifier: Error Notifier 1.0.11
		silk-all: Silk (All modules) 1.10.7
			silk-commands: Silk Commands 1.10.7
			silk-core: Silk Core 1.10.7
			silk-game: Silk Game 1.10.7
			silk-igui: Silk Inventory GUI 1.10.7
			silk-nbt: Silk NBT 1.10.7
			silk-network: Silk Network 1.10.7
			silk-persistence: Silk Persistence 1.10.7
		sodium: Sodium 0.6.0-beta.4+mc1.21.3
		sodium-extra: Sodium Extra 0.6.0-beta.4+mc1.21.3
		stack-to-nearby-chests: Stack to Nearby Chests 0.5.11
			libgui: LibGui 12.0.0+1.21.2
				jankson: Jankson 9.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		stackrefill: Stack Refill 4.5
		storagedrawers: Storage Drawers 14.0.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		taxfreelevels: Tax Free Levels 1.4.1
		timestacker: TimeStacker 1.2.1
		trade_cycling: Trade Cycling 1.21.3-1.0.15
		veinminer: Veinminer 2.2.0
			de_miraculixx_core: core 2.2.0
		veinminer-enchantment: Veinminer Enchantment 2.2.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		waystones: Waystones 21.3.3
		youritemsaresafe: Your Items Are Safe 4.5
	Launched Version: fabric-loader-0.16.9-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.0 Core Profile Context 24.5.1.240502, ATI Technologies Inc.
	Window size: 1920x1080
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 16/16 chunks
	Resource Packs: vanilla, file/VanillaTweaks_r879063_MC1.21.x.zip, fabric, axesareweapons, balm-fabric (incompatible), clean-debug, cloth-config, conditional-mixin, durabilitytooltip (incompatible), expandedstorage, extremesoundmuffler (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fluidtank, health_levels, inventorytweak, itemcollectors (incompatible), jade (incompatible), jamlib, jankson, kotori_scala, lambdynlights, libgui, merenc, midnightlib, modmenu, moreculling, mr_recipes_plus (incompatible), noexpensive, owo, pride, rightclickharvest, roughlyenoughitems, silk-all, sodium, sodium-extra, spruceui, stack-to-nearby-chests, storagedrawers, supermartijn642corelib (incompatible), taxfreelevels, trade_cycling, veinminer, veinminer-enchantment, waystones (incompatible)
	Current Language: en_us
	Locale: hu_HU
	System encoding: Cp1250
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['RustH077'/117, l='ServerLevel[New World]', x=-923.30, y=66.00, z=-518.96]]
	Active Data Packs: vanilla, fabric, axesareweapons, balm-fabric (incompatible), better_craftables, collective, expandedstorage, fabric-convention-tags-v2, fluidtank (incompatible), furnacerecycle, itemcollectors, moreculling, mr_nbc, mr_recipes_plus (incompatible), rightclickharvest, storagedrawers, supermartijn642corelib, veinminer-enchantment, waystones (incompatible)
	Available Data Packs: axesareweapons, balm-fabric (incompatible), better_craftables, collective, expandedstorage, fabric, fabric-convention-tags-v2, fluidtank (incompatible), furnacerecycle, itemcollectors, minecart_improvements, moreculling, mr_nbc, mr_recipes_plus (incompatible), redstone_experiments, rightclickharvest, storagedrawers, supermartijn642corelib, trade_rebalance, vanilla, veinminer-enchantment, waystones (incompatible), winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8634913831250405877
	Suppressed Exceptions: ~~NONE~~

**Comment by jaquadro** [comment]
Can you explain more how you produced the crash or why you think it's a Storage Drawers crash?

I don't see anything related to Storage Drawers in the stack track.  I've tried adding REI to my environment and checked various screens and items and didn't see anything happen.  So I'm going to need more info.
