### ISSUE TITLE
Exception Ticking World (1.7.10)  [only in dev environment?]

### ISSUE THREAD

**Issue by 1n5aN1aC** [jaquadro/StorageDrawers#154]
Having a hard time understanding why this is happening:

So the same version was working fine in our modpack a couple weeks ago, but now I was going to work on bettering the Logistics-Pipes integration, so I put the StorageDrawers jar inside the LP dev environment, and "got it working."  However, some time shortly after placing the drawer controller, with one adjacent compacting drawer, I get the following error:

    Description: Exception ticking world
    java.lang.NoSuchMethodError: com.jaquadro.minecraft.storagedrawers.api.storage.IDrawerGroup.getDrawerInventory()Lcom/jaquadro/minecraft/storagedrawers/api/inventory/IDrawerInventory;
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityController.updateRecordInfo(TileEntityController.java:390)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityController.populateNodes(TileEntityController.java:441)
	at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityController.updateCache(TileEntityController.java:261)
	at com.jaquadro.minecraft.storagedrawers.block.BlockController.updateTick(BlockController.java:162)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:408)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:191)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

To make sure it wasn't some kind of fluke, I tried it in a new world with a few different configurations, and placing a controller next to an empty compacting drawer instantly crashes every time.  any diea whats up?

**Comment by 1n5aN1aC** [comment]
Compacting drawers by themselves work perfectly in every situation as far as I can tell.  But drawer controllers explode as soon as they are placed, if next to a compacting drawer.

**Comment by jaquadro** [comment]
Is LP shipping my API?  (Or perhaps more likely, is the API included in your LP dev environment?)  It could be an out-of-date API, specifically before I started including package-info files to defuse those kinds of conflicts.

Make sure that if LP has a copy of the Storage Drawers API, that it is up to date.

**Comment by 1n5aN1aC** [comment]
mm thanks, I'm guessing that is it.

I guess I'll close this issue unless the issue re-occurs, in which case I'll re-open it.

Thanks!
