### ISSUE TITLE
Version 1.7.0 for minecraft 1.7.10 doesnt work on server side

### ISSUE THREAD

**Issue by bloodyraoul** [jaquadro/StorageDrawers#168]
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559) ~[Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)[li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
        at com.jaquadro.minecraft.storagedrawers.core.ModBlocks.init(ModBlocks.java:33) ~[ModBlocks.class:?]
        at com.jaquadro.minecraft.storagedrawers.StorageDrawers.preInit(StorageDrawers.java:73) ~[StorageDrawers.class:?]

**Comment by jaquadro** [comment]
Sorry, fixed in 1.7.1.  Dumb oversight on my part.
