### ISSUE TITLE
Model crash, excessively long bake

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#315]
Using the newest update (194321) results in a crash after a _very long_ (hit ~one hour however it should be noted that this is with other mods) bake process. Downgrading to 320 results in the same crash but no longer has the long bake period.

`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.AbstractStringBuilder.deleteCharAt(Unknown Source)
    at java.lang.StringBuilder.deleteCharAt(Unknown Source)
    at com.jaquadro.minecraft.chameleon.resources.ModelRegistry.getResourceLocation(ModelRegistry.java:139)
    at com.jaquadro.minecraft.chameleon.resources.ModelRegistry.loadModels(ModelRegistry.java:88)
    at com.jaquadro.minecraft.chameleon.core.ClientProxy.onModelBakeEvent(ClientProxy.java:25)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ClientProxy_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:392)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)`

Full log: http://paste.ee/p/3SVjm
The above was done using just SD+C for the sake of time.

Downgrading further to 3111 resolves the crash but spits out a huge amount of errors.

Full log: http://paste.ee/p/qz8Yw

**Comment by jaquadro** [comment]
The errors in your 3111 log are benign.

The crash in your other log is caused by Chameleon being out of date.  Upgrade that to 2.1.6.  As for the very long bake time, I have no idea.  I hope it just goes away when you upgrade Chameleon, but I have no intuition why it would happen in the first place.  Doesn't happen in my dev environment.
