### ISSUE TITLE
[1.10.2] (render)Crash at mp login

### ISSUE THREAD

**Issue by MakerTim** [jaquadro/StorageDrawers#326]
Crash at joining mp world
im standing right before some drawers and this crash is now every time i'm joining

full log: http://pastebin.com/uCDtjjec
`java.lang.NullPointerException: Tesselating block model
    at com.jaquadro.minecraft.storagedrawers.client.model.component.DrawerDecoratorModel.<init>(DrawerDecoratorModel.java:56)
    at com.jaquadro.minecraft.storagedrawers.client.model.CompDrawerModel$Model.buildModel(CompDrawerModel.java:81)
    at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.setProxy(ProxyBuilderModel.java:85)
    at com.jaquadro.minecraft.chameleon.model.ProxyBuilderModel.func_188616_a(ProxyBuilderModel.java:34)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
    at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:951)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by jaquadro** [comment]
What version of Forge?

**Comment by jaquadro** [comment]
For that matter, are you using the latest Storage Drawers?

**Comment by jaquadro** [comment]
Nevermind my previous comments, just saw your link to the full log.

**Comment by jaquadro** [comment]
For now, I'm going to trade one problem for another.  If you download 3.2.3, it should stop crashing your client.  But you might lose rendering of locks/fill bars/etc. on some drawers.  Let me know if it's widespread.

**Comment by MakerTim** [comment]
http://puu.sh/qzRfu.png
Everything looks like it supposed to
ty anyways!

started 4times without moving, and no crash at all
seems to be fixed
