### ISSUE TITLE
Right clicking drawers GM 3

### ISSUE THREAD

**Issue by ThomasAunvik** [jaquadro/StorageDrawers#455]
Right Clicking drawers in gamemode 3 gives out an error. or i should say, it kicks you out of the server with this error:
![Draw](http://i.imgur.com/joWAv5Y.png)

**Comment by jaquadro** [comment]
I didn't even know there was a gamemode 3.

Can you attach a server log?

**Comment by ThomasAunvik** [comment]
Quote from https://github.com/CyclopsMC/IntegratedDynamics/issues/164

> error when trying it in SSP:

```
Caused by: java.lang.NullPointerException
	at net.minecraft.inventory.InventoryBasic.<init>(InventoryBasic.java:33) ~[InventoryBasic.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleOpenWindow(NetHandlerPlayClient.java:1154) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.SPacketOpenWindow.processPacket(SPacketOpenWindow.java:47) ~[SPacketOpenWindow.class:?]
	at net.minecraft.network.play.server.SPacketOpenWindow.processPacket(SPacketOpenWindow.java:11) ~[SPacketOpenWindow.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0]
	at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
```

**Comment by ThomasAunvik** [comment]
Nothing useful info in the server log, but i got the client log that gives out two exceptions
https://pastebin.com/V829gvsA

[Full Client Log](https://gist.github.com/ThomasAunvik/f0505f9f0878a7fa235e01b0c23f7de2)

[Server Log](https://pastebin.com/nXbTAERL)

Edit:
I tested it in singleplayer and it gave no errors or exceptions. It seems it only does it in servers.

**Comment by ouroborus** [comment]
gamemode 3 is spectator mode. A lot of custom containers act weird in this mode.
