### ISSUE TITLE
1.11.2 crash because of missing code in the mod?

### ISSUE THREAD

**Issue by croftyraider** [jaquadro/StorageDrawers#517]
I have some farms running (actually additions) with mekanism pipe's used to connect to a drawer controller to distribute the items from the farm to various drawers.

version is 1.11.2-4.2.9

````
java.lang.NoSuchMethodError: com.jaquadro.minecraft.storagedrawers.api.storage.IDrawer.getDefaultMaxCapacity()I
	at com.jaquadro.minecraft.storagedrawers.inventory.DrawerItemHandler.getSlotLimit(DrawerItemHandler.java:184)
	at mekanism.common.content.transporter.TransporterManager.getPredictedInsert(TransporterManager.java:605)
	at mekanism.common.transmitters.grid.InventoryNetwork.calculateAcceptors(InventoryNetwork.java:65)
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:244)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:318)
	at mekanism.common.content.transporter.TransporterPathfinder$IdlePath.find(TransporterPathfinder.java:78)
	at mekanism.common.content.transporter.TransporterPathfinder.getIdlePath(TransporterPathfinder.java:574)
	at mekanism.common.content.transporter.TransporterStack.calculateIdle(TransporterStack.java:227)
	at mekanism.common.transmitters.TransporterImpl.recalculate(TransporterImpl.java:246)
	at mekanism.common.transmitters.TransporterImpl.update(TransporterImpl.java:174)
	at mekanism.common.tile.transmitter.TileEntityLogisticalTransporter.func_73660_a(TileEntityLogisticalTransporter.java:126)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
````

**Comment by croftyraider** [comment]
FYI I tried the previous version but no love there. Right now as it stands my world won't load because of the crash.

**Comment by codewarrior0** [comment]
Looks like #492.

**Comment by croftyraider** [comment]
I updated my refined storage version and all is well, thanks for the quick pointer to the solution :) This can be closed I guess. Seems like a shame to run into such issues... Maybe what King Lemming is doing with the RF API should be done here too for 1.12 to avoid this sort of thing?

See https://www.reddit.com/r/feedthebeast/comments/6jinzo/psa_the_rf_api_will_be_a_signed_standalone_jar/

**Comment by jaquadro** [comment]
My advice to the RS project was to reference the API via the gradle api source set, so they could still be packed into the repo for convenience, but they would not be shipped in a build.  It seems to work well for soft dependencies like this.  Making it available through Maven would be better, but neither case really calls for an independent API jar to take a hard dependency on.

**Comment by jaquadro** [comment]
We came up with a better solution for 1.12, so this is unlikely to surface again.
