### ISSUE TITLE
[1.12] Crash when placing item into something else while holding a lock key. 

### ISSUE THREAD

**Issue by shadow306k** [jaquadro/StorageDrawers#635]
> The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraftforge.items.wrapper.EmptyHandler cannot be cast to com.jaquadro.minecraft.storagedrawers.api.storage.IDrawerAttributes

I was holding the key in my off-hand while placing an Oak Sapling into the Hopping Bonsai Pot from the Bonsai Trees mod, and the game crashed with this error. Not sure if it's a compatibility issue or something else.

**Comment by L3thal1ty** [comment]
I was just logging in to post this bug. I am having the same problem with the same mod on Modern Skyblock 3.

**Comment by jaquadro** [comment]
Can you post the full stacktrace?

**Comment by L3thal1ty** [comment]
I am not super proficient with crash logs and the associated terminology, so if this isn't what you're looking for, please tell me how to find what you're looking for.

-- Head --
Thread: Client thread
Stacktrace:
	at com.jaquadro.minecraft.storagedrawers.item.ItemKey.func_180614_a(ItemKey.java:63)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:477)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

**Comment by codewarrior0** [comment]
This appears to be a bug in Bonsai Trees; see https://github.com/thraaawn/BonsaiTrees/issues/37
