### ISSUE TITLE
Crash after working normally the day before

### ISSUE THREAD

**Issue by Elsker99** [jaquadro/StorageDrawers#744]
`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/25/19 10:08 AM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.replaceBlock(BasicDrawerModel.java:204) ~[?:1.14.4-6.0.5] {}
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.registerModels(BasicDrawerModel.java:162) ~[?:1.14.4-6.0.5] {}
	at net.minecraftforge.eventbus.ASMEventHandler_93_Register_registerModels_ModelBakeEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:28.1] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:240) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader$$Lambda$3173/4061472.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:240) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:366) ~[?:?] {}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3367/1476855945.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader$$Lambda$3500/1079554968.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:858) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.10.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$354/583351682.call(Unknown Source) [forge-1.14.4-28.1.10.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.replaceBlock(BasicDrawerModel.java:204)
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.registerModels(BasicDrawerModel.java:162)
	at net.minecraftforge.eventbus.ASMEventHandler_93_Register_registerModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:240)
	at net.minecraftforge.fml.ModLoader$$Lambda$3173/4061472.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:240)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:366)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at net.minecraft.client.resources.ReloadListener$$Lambda$3367/1476855945.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$3500/1079554968.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:882)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:887)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$354/583351682.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7458115256 bytes (7112 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.10
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		AmbientSounds_v3.0.11_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		Apotheosis-1.14.4-2.3.3.jar Apotheosis {apotheosis@2.3.3 CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.12 (1).jar AppleSkin {appleskin@1.0.12 CREATE_REGISTRIES}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 CREATE_REGISTRIES}
		bambooeverything-1.14-1.4.0.jar Bamboo Everything {bambooeverything@1.14-1.4.0 CREATE_REGISTRIES}
		BasicNetherOres-1.14.4-3.2.1.jar Basic Nether Ores {bno@3.2.1 CREATE_REGISTRIES}
		betteranimalsplus-1.14.4-7.1.2.jar Better Animals Plus {betteranimalsplus@7.1.2 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.253-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.253 CREATE_REGISTRIES}
		BioTechnik-1.14.4-1.0.1.jar Bio Technik {biotechnik@1.0.1 CREATE_REGISTRIES}
		buildinggadgets-3.0.5.jar Building Gadgets {buildinggadgets@3.0.5 CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 CREATE_REGISTRIES}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 CREATE_REGISTRIES}
		corail_woodcutter-1.0.3-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.3 CREATE_REGISTRIES}
		CraftingTweaks_1.14.4-10.1.3.jar Crafting Tweaks {craftingtweaks@10.1.3 CREATE_REGISTRIES}
		create-mc1.14.4_v0.1.0.jar Create {create@0.1.0 CREATE_REGISTRIES}
		Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 CREATE_REGISTRIES}
		Cursed-Earth-1.14.4.jar Cursed Earth {cursedearth@1.2 CREATE_REGISTRIES}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 CREATE_REGISTRIES}
		dankstorage-1.4a.jar Dank Storage {dankstorage@1.4a CREATE_REGISTRIES}
		Druidcraft-1.14-0.1.3.jar Druidcraft {druidcraft@0.1.12 ERROR}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 CREATE_REGISTRIES}
		embellishcraft-1.14.4-1.0.0.jar EmbellishCraft {embellishcraft@1.14.4-1.0.0 CREATE_REGISTRIES}
		endercompass-1.1.jar Ender Compass {endercompass@1.1 CREATE_REGISTRIES}
		engineersdecor-1.14.4-1.0.13-b1.jar Engineer's Decor {engineersdecor@1.0.13-b1 CREATE_REGISTRIES}
		engineerstools-1.14.4-1.0.3-b2.jar Engineer's Tools {engineerstools@1.0.3-b2 CREATE_REGISTRIES}
		essentials-1.14.4-2.5.0.jar Essentials {essentials@1.14.4-2.5.0 CREATE_REGISTRIES}
		Extended-Lights-Mod-1.14.4.jar Extended Lights {extlights@1.2 CREATE_REGISTRIES}
		Extra-Enrichments-1.14.4.jar Extra Enrichments {extraenrichments@1.1.1 CREATE_REGISTRIES}
		extraboats-1.0.4-1.14.4.jar Extra Boats {extraboats@1.0.4 CREATE_REGISTRIES}
		extragolems-9.0.0-beta.jar Extra Golems {golems@TODO-golems_version CREATE_REGISTRIES}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 CREATE_REGISTRIES}
		ferroustry-1.3a.jar Ferroustry {ferroustry@1.3a CREATE_REGISTRIES}
		forbidden_arcanus-1.14.4-1.1.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.0-Beta-4 CREATE_REGISTRIES}
		furniture-7.0.0-pre10-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre10 CREATE_REGISTRIES}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 CREATE_REGISTRIES}
		good-nights-sleep-1.14.4-0.3.1.jar Good Night's Sleep {goodnightsleep@0.3.1 CREATE_REGISTRIES}
		Heaven-Paradise-Plant-1.14.4.jar Heaven Paradise Plant {heavenparadiseplantmod@1.0.0 CREATE_REGISTRIES}
		Hwyla-forge-1.10.5-B66_1.14.4.jar Waila {waila@version CREATE_REGISTRIES}
		inventorysorter-1.14.4-16.0.0.jar Simple Inventory Sorter {inventorysorter@16.0.0 CREATE_REGISTRIES}
		ironchest-1.14.3-9.0.DEV.55a7af2.jar Iron Chests {ironchest@1.14.3-9.0.DEV.55a7af2 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 CREATE_REGISTRIES}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 CREATE_REGISTRIES}
		mcjtylib-1.14-3.5.7-alpha.jar McJtyLib {mcjtylib@NONE CREATE_REGISTRIES}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c CREATE_REGISTRIES}
		mining_dimension-1.14.4-1.0.8.jar Mining World {mining_dimension@1.14.4-1.0.8 CREATE_REGISTRIES}
		morecharcoal-1.14.4-4.jar More Charcoal {morecharcoal@1.14.4-4 CREATE_REGISTRIES}
		mysticalwildlife-1.14.4-1.3.2.jar Mystical Wildlife {mysticalwildlife@1.3.2 CREATE_REGISTRIES}
		Neat+1.5-19.jar Neat {neat@1.5-19 CREATE_REGISTRIES}
		PackingTape-1.14.4-0.8.4.jar Packing Tape {packingtape@0.8.4 CREATE_REGISTRIES}
		PickleTweaks-1.14.4-3.0.4.jar Pickle Tweaks {pickletweaks@3.0.4 CREATE_REGISTRIES}
		Placebo-1.14.4-2.2.1.jar Placebo {placebo@2.2.1 CREATE_REGISTRIES}
		randompatches-1.14.4-1.18.2.1.jar RandomPatches {randompatches@1.14.4-1.18.2.1 CREATE_REGISTRIES}
		reap-1.10.1.jar Reap Mod {reap@1.10.1 CREATE_REGISTRIES}
		rftoolsbase-1.14-0.0.4-alpha.jar RFToolsBase {rftoolsbase@NONE CREATE_REGISTRIES}
		rsgauges-1.14.4-1.1.8-b3.jar Redstone Gauges and Switches {rsgauges@1.1.8-b3 CREATE_REGISTRIES}
		searchablechests-1.5.1.jar Searchable Chests {searchablechests@1.5.1 CREATE_REGISTRIES}
		SilentGear-1.14.4-1.4.1+66.jar Silent Gear {silentgear@1.4.1+66 CREATE_REGISTRIES}
		SilentGems-1.14.4-3.4.2+75.jar Silent's Gems 3 {silentgems@3.4.2+75 CREATE_REGISTRIES}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 CREATE_REGISTRIES}
		SilentMechanisms-1.14.4-0.6.0+31.jar Silent's Mechanisms {silents_mechanisms@0.6.0+31 CREATE_REGISTRIES}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 CREATE_REGISTRIES}
		StorageDrawers-1.14.4-6.0.5 (1).jar Storage Drawers {storagedrawers@1.14.4-6.0.3 CREATE_REGISTRIES}
		structurize-0.10.157-ALPHA.jar Structurize {structurize@unspecified CREATE_REGISTRIES}
		themidnight-0.4.5.jar The Midnight {midnight@0.4.5 CREATE_REGISTRIES}
		tombstone-4.1.3-1.14.4.jar Corail Tombstone {tombstone@4.1.3 CREATE_REGISTRIES}
		Trinity-1.14.4-1.2.0.jar Trinity {trinity@1.2.0 CREATE_REGISTRIES}
		u_team_core-1.14.4-2.7.1.130.jar U Team Core {uteamcore@2.7.1.130 CREATE_REGISTRIES}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 CREATE_REGISTRIES}
		VanillaTweaks-1.14.4.1.5.7.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.7 CREATE_REGISTRIES}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 CREATE_REGISTRIES}
		Xaeros_Minimap_1.18.2_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.2 CREATE_REGISTRIES}
		XaerosWorldMap_1.4.10.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.10.1 CREATE_REGISTRIES}
		XL-Food-Mod-1.14.4-2.0.3.jar XL Food Mod {xlfoodmod@2.0.3 CREATE_REGISTRIES}
		forge-1.14.4-28.1.10-universal.jar Forge {forge@28.1.10 CREATE_REGISTRIES}
		forge-1.14.4-28.1.10-client.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
	Launched Version: 1.14.4-forge-28.1.10
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.15, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz`

**Comment by Elsker99** [comment]
Okay i did some fiddling around and it turns out it's incomparable with donk storage at the moment.

Closing this
