### ISSUE TITLE
[1.15.1] Crash while looking at drawers 

### ISSUE THREAD

**Issue by muffe** [jaquadro/StorageDrawers#797]
Running `forge-30.0.50`

After I put another storage drawer in a storage drawer my game now crashes as soon as I look at the drawer.

```
Description: Rendering Block Entity

java.lang.NoSuchMethodError: net.minecraft.client.renderer.model.IBakedModel.func_230044_c_()Z
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderFastItem(TileEntityDrawersRenderer.java:175) ~[?:1.15.2-7.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderFastItemSet(TileEntityDrawersRenderer.java:95) ~[?:1.15.2-7.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.render(TileEntityDrawersRenderer.java:65) ~[?:1.15.2-7.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.func_225616_a_(TileEntityDrawersRenderer.java:29) ~[?:1.15.2-7.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$4168/413834115.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:423) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.50.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/1326998608.call(Unknown Source) [forge-1.15.1-30.0.50.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderFastItem(TileEntityDrawersRenderer.java:175)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.renderFastItemSet(TileEntityDrawersRenderer.java:95)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.render(TileEntityDrawersRenderer.java:65)
	at com.jaquadro.minecraft.storagedrawers.client.renderer.TileEntityDrawersRenderer.func_225616_a_(TileEntityDrawersRenderer.java:29)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$func_228850_a_$0(TileEntityRendererDispatcher.java:84)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$4168/413834115.run(Unknown Source)

-- Block Entity Details --
Details:
	Name: storagedrawers:standard_drawers_4 // com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard.Slot4
	Block: Block{storagedrawers:acacia_half_drawers_4}[facing=north]
	Block location: World: (-763,61,28), Chunk: (at 5,3,12 in -48,1; contains blocks -768,0,16 to -753,255,31), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Block: Block{storagedrawers:acacia_half_drawers_4}[facing=north]
	Block location: World: (-763,61,28), Chunk: (at 5,3,12 in -48,1; contains blocks -768,0,16 to -753,255,31), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:124)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:83)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:980)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:601)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['muffe2k'/136, l='MpServer', x=-762.61, y=60.00, z=24.97]]
	Chunk stats: Client Chunk Cache: 729, 116
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -1434198979052628876
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,80,-110), Chunk: (at 0,5,2 in 0,-7; contains blocks 0,0,-112 to 15,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 46512080 game time, 30572 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1719)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:534)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/1326998608.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 648273200 bytes (618 MB) / 1905262592 bytes (1817 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.50.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.50.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.50.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.50.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.50.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.50
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.50-client.jar Minecraft {minecraft@1.15.1 DONE}
		useful_backpacks-1.15.1-1.8.3.51.jar Useful Backpacks {usefulbackpacks@1.8.3.51 DONE}
		u_team_core-1.15.1-2.9.3.145.jar U Team Core {uteamcore@2.9.3.145 DONE}
		BiomesOPlenty-1.15.1-10.0.0.296-universal.jar Biomes O' Plenty {biomesoplenty@1.15.1-10.0.0.296 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		Apotheosis-1.15.1-3.0.2.jar Apotheosis {apotheosis@3.0.2 DONE}
		Waddles-1.15.1-0.8.4.jar Waddles {waddles@1.15.1-0.8.4 DONE}
		Hwyla-forge-1.10.7-B71_1.15.1.jar Waila {waila@version DONE}
		jei-1.15.1-6.0.0.1.jar Just Enough Items {jei@6.0.0.1 DONE}
		XL-Food-Mod-1.15.1-2.2.1.jar XL Food Mod {xlfoodmod@2.2.1 DONE}
		forge-1.15.1-30.0.50-universal.jar Forge {forge@30.0.50 DONE}
		FastLeafDecay-v19.jar FastLeafDecay {fastleafdecay@v19 DONE}
		gravestone-1.16.2.jar Gravestone Mod {gravestone@1.16.2 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		Placebo-1.15.1-3.0.0.jar Placebo {placebo@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.0.jar Storage Drawers {storagedrawers@1.15.2-7.0.0 DONE}
	Launched Version: forge-30.0.50
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
```

**Comment by jaquadro** [comment]
This turned out to be a difference between MC 1.15.1 and 1.15.2.

The difference doesn't look very important, so I have reverted that part to an older call and that should resolve the problem.

There's a new release up now that should run without crashing.
