### ISSUE TITLE
1.8-2.0.0a4 Compacting Drawers don't place and have a bad damage value

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawers#80]
![Image of Compacting Drawers that can't be placed](http://i.imgur.com/odd0iJD.png)

There is no server console spam or errors that I can see.

The client is throwing a FATAL however when I try to place them and they of course vanish when I do that. The following appears everytime I try to place one.

```
[15:41:04] [Client thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.ClassCastException
java.util.concurrent.ExecutionException: java.lang.ClassCastException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_45]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_45]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:710) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1011) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException
```

**Comment by jaquadro** [comment]
Does it mention anywhere what class it's trying to cast from?

**Comment by kreezxil** [comment]
Ok, that error might not belong to you. But what about the compacting drawers, are you able to craft them? Have you tested it in SMP 1.8?

**Comment by jaquadro** [comment]
It looks like the recipe is broken.  It'll be fixed in the next alpha, which should be soonish.  Finally making some headway on the upgrade rendering bits.

**Comment by kreezxil** [comment]
Awesome

-----Original Message-----

**Comment by jaquadro** [comment]
Fixed in alpha 5.

**Comment by kreezxil** [comment]
You're right it is fixed! :)
