### ISSUE TITLE
1.14 Rendering overlay

### ISSUE THREAD

**Issue by pghvbrothers** [jaquadro/StorageDrawers#805]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/5/20 4:48 PM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.replaceBlock(BasicDrawerModel.java:204) ~[?:1.14.4-6.0.6] {re:classloading}
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.registerModels(BasicDrawerModel.java:162) ~[?:1.14.4-6.0.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_146_Register_registerModels_ModelBakeEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:28.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2348/23258671.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:380) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3290/1104137141.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$$Lambda$3440/561234803.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.116.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/892093608.call(Unknown Source) [forge-1.14.4-28.1.116.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.replaceBlock(BasicDrawerModel.java:204)
	at com.jaquadro.minecraft.storagedrawers.client.model.BasicDrawerModel$Register.registerModels(BasicDrawerModel.java:162)
	at net.minecraftforge.eventbus.ASMEventHandler_146_Register_registerModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243)
	at net.minecraftforge.fml.ModLoader$$Lambda$2348/23258671.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:380)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:58)
	at net.minecraft.client.renderer.model.ModelManager.func_212853_a_(ModelManager.java:17)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at net.minecraft.client.resources.ReloadListener$$Lambda$3290/1104137141.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$3440/561234803.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:880)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/892093608.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1580346952 bytes (1507 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.116.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.116.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.116
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		followingvillagers-1.14.4-1.2.0.jar Following Villagers {followingvillagers@1.14.4-1.2.0 CREATE_REGISTRIES}
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 CREATE_REGISTRIES}
		Ma-Enchants-1.14.4-1.8.1.jar Ma Enchants {ma-enchants@1.14.4-1.8.1 CREATE_REGISTRIES}
		mining-helmet-1.14.4-1.0.2.jar Mining Helmet {mining_helmet@1.0.2 CREATE_REGISTRIES}
		upsizer-mc1.14.4-5.0b4.jar Upsizer {upsizer@5.0.0b4 CREATE_REGISTRIES}
		bambooblocks-1.2.11.jar Bamboo Blocks {bambooblocks@1.2.11 CREATE_REGISTRIES}
		vilnames_1.14-1.4.jar Villager Names {vilnames@1.4 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 CREATE_REGISTRIES}
		EverlastingAbilities-1.14.4-1.6.0.jar EverlastingAbilities {everlastingabilities@1.6.0 CREATE_REGISTRIES}
		ensorcellation-1.14.4-0.2.0b.jar Ensorcellation {ensorcellation@0.2.0b CREATE_REGISTRIES}
		Waystones_1.14.4-5.1.0.jar Waystones {waystones@5.1.0 CREATE_REGISTRIES}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 CREATE_REGISTRIES}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 CREATE_REGISTRIES}
		RingOfRepair-1.14.4-1.0.21.jar Ring of Repair {ring_of_repair@1.0.21 CREATE_REGISTRIES}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 CREATE_REGISTRIES}
		comforts-FORGE-1.14.4-2.0-beta4.jar Comforts {comforts@FORGE-1.14.4-2.0-beta4 CREATE_REGISTRIES}
		EnderBags-1.14.4-4.2.0.jar Ender Bags {ender_bags@4.2.0 CREATE_REGISTRIES}
		PyramidPlunder-1.14.4-1.1.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 CREATE_REGISTRIES}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		branders-enhanced-mob-spawners-v1.14.4-1.4.3.jar Enhanced Mob Spawners {spawnermod@1.4.4 CREATE_REGISTRIES}
		Bookshelf-1.14.4-4.4.71.jar Bookshelf {bookshelf@4.4.71 CREATE_REGISTRIES}
		BotanyPots-1.14.4-1.0.8.jar BotanyPots {botanypots@1.0.8 CREATE_REGISTRIES}
		cofh_core-1.14.4-0.2.0b.jar CoFH Core {cofh_core@0.2.0b CREATE_REGISTRIES}
		u_team_core-1.14.4-2.8.0.140.jar U Team Core {uteamcore@2.8.0.140 CREATE_REGISTRIES}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version CREATE_REGISTRIES}
		forge-1.14.4-28.1.116-universal.jar Forge {forge@28.1.116 CREATE_REGISTRIES}
		exp_bottling-1.14.4-4.jar EXP Bottling {exp_bottling@1.14.4-4 CREATE_REGISTRIES}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 CREATE_REGISTRIES}
		forge-1.14.4-28.1.116-client.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 ERROR}
		useful_backpacks-1.14.4-1.7.4.47.jar Useful Backpacks {usefulbackpacks@1.7.4.47 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.9.jar EnchantmentDescriptions {enchdesc@1.3.9 CREATE_REGISTRIES}
		embellishcraft-1.14.4-1.5.0.jar EmbellishCraft {embellishcraft@1.14.4-1.5.0 CREATE_REGISTRIES}
		watercan-1.14.4-2.1.0.jar Watercan {watercan@1.14.4-2.1.0 CREATE_REGISTRIES}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 ERROR}
		pamhc2crops-1.14.4-1.0.3.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version CREATE_REGISTRIES}
		LetSleepingDogsLie-1.14.4-1.1.0.jar Let Sleeping Dogs Lie {dogslie@1.1.0 CREATE_REGISTRIES}
		Masonry-0.3.1.jar Masonry {masonry@1.0 CREATE_REGISTRIES}
		simplefarming-1.14.4-1.2.7.jar Simple Farming {simplefarming@1.14.4-1.2.7 CREATE_REGISTRIES}
		BerryBushes-1.0.2.jar Berry Bushes {berrybushes@1.0.2 CREATE_REGISTRIES}
		ffenchants-1.14.4-1.2.4.jar FlashFyre's Enchantments {ffenchants@1.2.4 CREATE_REGISTRIES}
		corail_woodcutter-1.1.1-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.1.1 CREATE_REGISTRIES}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 CREATE_REGISTRIES}
		gravestone-1.15.2.jar Gravestone Mod {gravestone@1.15.2 CREATE_REGISTRIES}
		StorageDrawers-1.14.4-6.0.6.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 CREATE_REGISTRIES}
		Ore-Excavation-Mod-1.14.4.jar Ore Excavation {oreexcavation@1.6.145 CREATE_REGISTRIES}
		vanillahammers-1.14.4-1.0.jar Vanilla Hammers {vanillahammers@1.14.4-1.0 CREATE_REGISTRIES}
		polyores-1.2.jar Poly's Ores {polyores@1.2 CREATE_REGISTRIES}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version CREATE_REGISTRIES}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 CREATE_REGISTRIES}
		StorageDrawersUnlimited-1.14.4-1.3.4.jar Storage Drawers Unlimited {storagedrawersunlimited@1.14.4-1.3.4 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		mobcatcher-1.2b.jar Mob Catcher {mobcatcher@1.2b CREATE_REGISTRIES}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 CREATE_REGISTRIES}
		CHAS+v1.3+for+1.14.jar Craftable Horse Armour {craftablehorsearmour@1.3 CREATE_REGISTRIES}
		Charm-1.14.4-1.4.3.jar Charm {charm@1.14.4-1.4.3 CREATE_REGISTRIES}
		Quark-r2.0-209.jar Quark {quark@r2.0-209 CREATE_REGISTRIES}
		More+Dogs-1.0.1.jar More Dog Breeds {moredogs@1.0.1 CREATE_REGISTRIES}
		supertools-1.14.4-2.3.jar Vanilla+ Tools {supertools@version CREATE_REGISTRIES}
		TrinityWeapons-1.14.4-1.4.0.jar TrinityWeapons {trinity@1.4.0 CREATE_REGISTRIES}
	Launched Version: 1.14.4-forge-28.1.116
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by jaquadro** [comment]
Both "Titanium" and "Industrial Foregoing" mods are in an error state in your list, so they probably crashed earlier in the process.  Try taking them out or seeing if there's an update.
