### ISSUE TITLE
AStral Sorcery Formation Wand crash

### ISSUE THREAD

**Issue by PKArtKat** [jaquadro/StorageDrawers#894]
There is an issue with the Formation Wand from Astral Sorcery that causes a crash when it passes over a drawer. i have told the Astral Sorcery team and they said it was an issue needed to be brought up here.

**Comment by Jeuvke** [comment]
https://github.com/jaquadro/StorageDrawers/blob/1.15/src/main/java/com/jaquadro/minecraft/storagedrawers/block/BlockDrawers.java#L235

.getPlayer can be null, this is explicitly defined as such.

**Comment by andrewsf** [comment]
Fifth distinct mod this month for me that caused a crash trying to use a null `getPlayer()`.

Here's a stack trace since the original report is so sparse:

```
java.lang.NullPointerException: Unexpected error
	at com.jaquadro.minecraft.storagedrawers.block.BlockDrawers.func_196253_a(BlockDrawers.java:234) ~[?:1.16.3-8.2.1] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196953_a(AbstractBlock.java:663) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.item.BlockItemUseContext.<init>(SourceFile:32) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at hellfirepvp.astralsorcery.common.util.block.TestBlockUseContext.<init>(TestBlockUseContext.java:35) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.util.block.TestBlockUseContext.getHandContextWithItem(TestBlockUseContext.java:44) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.util.block.TestBlockUseContext.getHandContext(TestBlockUseContext.java:40) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.util.block.BlockUtils.isReplaceable(BlockUtils.java:92) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.util.block.BlockUtils.isReplaceable(BlockUtils.java:85) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand$PlaceMode$1.lambda$generatePlacementPositions$0(ItemArchitectWand.java:342) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand$PlaceMode$1$$Lambda$32111/1668313227.get(Unknown Source) ~[?:?] {}
	at hellfirepvp.astralsorcery.common.util.MiscUtils.executeWithChunk(MiscUtils.java:575) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand$PlaceMode$1.generatePlacementPositions(ItemArchitectWand.java:342) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand.getPlaceStates(ItemArchitectWand.java:257) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand.getPlayerPlaceableStates(ItemArchitectWand.java:235) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.common.item.wand.ItemArchitectWand.renderInHand(ItemArchitectWand.java:99) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.client.event.ItemHeldEffectRenderer.doHeldRender(ItemHeldEffectRenderer.java:60) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.client.event.ItemHeldEffectRenderer.onHeldRender(ItemHeldEffectRenderer.java:48) ~[?:1.16.4-1.13.1] {re:classloading}
	at hellfirepvp.astralsorcery.client.event.ItemHeldEffectRenderer$$Lambda$10641/1561973179.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2977/979049207.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:150) ~[?:?] {re:classloading}
```

Storage Drawers: 8.2.1
Astral Sorcery: 1.13.1
Forge: 35.1.4
Minecraft: 1.16.4

**Comment by Lejoni** [comment]
[crash-2020-12-04_11.41.10-client.txt](https://github.com/jaquadro/StorageDrawers/files/5642601/crash-2020-12-04_11.41.10-client.txt)
Here is a crash report related to this bug as well if that helps.
