### ISSUE TITLE
Crash on Storage Drawer being placed by automation

### ISSUE THREAD

**Issue by chainingsolid** [jaquadro/StorageDrawers#895]
Mods involved:
-Storage Drawers 8.2.1
-Create: with a self built jar non offical

Crash:
>  at com.jaquadro.minecraft.storagedrawers.block.BlockDrawers.func_180633_a(BlockDrawers.java:219) ~[storagedrawers:1.16.3-8.2.1] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.LaunchedItem$ForBlockState.place(LaunchedItem.java:145) ~[create:mc1.16.3_v0.3+custom] {re:classloading}
at com.simibubi.create.content.schematics.block.LaunchedItem.update(LaunchedItem.java:63) ~[create:mc1.16.3_v0.3+custom] {re:classloading}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.tickFlyingBlocks(SchematicannonTileEntity.java:757) ~[create:mc1.16.3_v0.3+custom] {re:classloading,pl:runtimedistcleaner:A}
at com.simibubi.create.content.schematics.block.SchematicannonTileEntity.func_73660_a(SchematicannonTileEntity.java:291) ~[create:mc1.16.3_v0.3+custom] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
... 5 more 

Line where crash occurs linked for convience
https://github.com/jaquadro/StorageDrawers/blob/fc9157e31ba22ac3976227d01d5dbcfeb057b8e9/src/main/java/com/jaquadro/minecraft/storagedrawers/block/BlockDrawers.java#L219
The crash appears to be caused by use of the "LivingEntity entity" argument, being null 
-The source code I used to build the jar file for the create mod that I'm using does pass null for that argument
-The reason I'm reporting this here and not on create's issue tracker is that, at least in my 1.16 dev enviorment that argument is tagged "@Nullable", in Block.class

**Comment by LordGrimmauld** [comment]
I just wanted to report this myself. Well, the nullable is there in 1.15 too. And Create is not the only mod passing null to the onBlockPlacedBy. Iirc quark does that too for placement by dispenser.

**Comment by ali1234** [comment]
There is a pull request to fix this: https://github.com/jaquadro/StorageDrawers/pull/786
